[
    {
        "unitypath":"Applications/Unity_appstore_n1",
        "name":"lianwufree",
        "bundleid":"com.ddianle.lovedance.$(PRODUCT_NAME)",
        "apkversion":"47",
        "customversion":"174",
        "bundleversion":"1.6.0523",
        "premacro":"PARTER_IOS;PACKAGE_DYNAMICDOWNLOAD",
        "mods":[
            {
                "group":"",
                "libs":[
                    "libz.dylib",
                    "libsqlite3.0.dylib",
                    "libz.1.2.5.dylib",
                    "libicucore.dylib",
                    "libstdc++.dylib"
                ],
                "frameworks":[
                    "MapKit.framework",
                    "ImageIO.framework",
                    "MessageUI.framework",
                    "Security.framework",
                    "MobileCoreServices.framework",
                    "CoreTelephony.framework",
                    "StoreKit.framework",
                    "AddressBook.framework",
                    "JavaScriptCore.framework",
                    "AdSupport.framework",
                    "Contacts.framework"
                ],
                "headerpaths":[

                ],
                "files":[
                    "Config.zip"
                ],
                "folders":[
                    "interface",
                    "Res:ref",
                    "www:ref",
                    "www_userSystem:ref",
                    "common"
                ],
                "excludes":[
                    "^.*.meta$",
                    "^.*.mdown$",
                    "^.*.pdf$",
                    ".DS_Store"
                ],
                "linker_flags":[
                    "-ObjC",
                    "-licucore",
                    "-lz",
                    "-all_load"
                ],
                "compiler_flags":[

                ]
            }
        ],
        "devsign":"iPhone Developer: shijun wang (3LHUC57LGR)",
        "dissign":"iPhone Distribution: Shanghai Lelian Information Technology Co., Ltd (C259Q68AGC)",
        "urlschemes":[

        ],
        "otherfiles":[
            "Info.plist",
            "Classes/UnityAppController.h",
            "Classes/UnityAppController.mm",
            "Unity-iPhone/Images.xcassets"
        ],
        "appcontrollerpath":"",
        "devprofile":"0db2f7da-431e-48bc-99b4-68f09bf9ddc3",
        "pubprofile":"60a78d87-6513-4f43-a89a-dbcacea0835d",
        "isselected":true,
        "appcontroller":"",
        "inhoursesign":"iPhone Developer: shijun wang (3LHUC57LGR)",
        "inhourseprofile":"e72be56f-4d0e-493c-a2c1-afc70f0e7d81",
        "buildallipa":true
    },
    {
        "unitypath":"Applications/Unity_appstore_n1",
        "name":"ddl",
        "bundleid":"com.ddianle.lovedance.$(PRODUCT_NAME)",
        "apkversion":"29",
        "customversion":"70",
        "bundleversion":"1.4.0906",
        "premacro":"PARTER_IOS;VERSION_CHARGE;PACKAGE_DYNAMICDOWNLOAD",
        "mods":[
            {
                "group":"",
                "libs":[
                    "libz.dylib",
                    "libsqlite3.0.dylib",
                    "libz.1.2.5.dylib"
                ],
                "frameworks":[
                    "MapKit.framework",
                    "ImageIO.framework",
                    "MessageUI.framework",
                    "Security.framework",
                    "MobileCoreServices.framework",
                    "CoreTelephony.framework",
                    "StoreKit.framework",
                    "AddressBook.framework",
                    "JavaScriptCore.framework",
                    "AdSupport.framework"
                ],
                "headerpaths":[

                ],
                "files":[
                    "Config.zip"
                ],
                "folders":[
                    "interface",
                    "Res:ref",
                    "www:ref",
                    "www_userSystem:ref",
                    "common"
                ],
                "excludes":[
                    "^.*.meta$",
                    "^.*.mdown$",
                    "^.*.pdf$",
                    ".DS_Store"
                ],
                "linker_flags":[
                    "-ObjC",
                    "-licucore",
                    "-lz",
                    "-all_load"
                ],
                "compiler_flags":[

                ]
            }
        ],
        "devsign":"iPhone Distribution: LoveDance Technology Co., Ltd.",
        "dissign":"iPhone Distribution: LoveDance Technology Co., Ltd.",
        "urlschemes":[

        ],
        "otherfiles":[
            "Info.plist",
            "Classes/UnityAppController.h",
            "Classes/UnityAppController.mm",
            "Unity-iPhone/Images.xcassets"
        ],
        "appcontrollerpath":"",
        "devprofile":"3f6f6cad-a063-4d05-bb57-44e69e5b203c",
        "pubprofile":"c445eda0-c5e4-481b-9929-e34a8e862a40",
        "isselected":false,
        "appcontroller":"",
        "inhoursesign":"iPhone Distribution: LoveDance Technology Co., Ltd.",
        "inhourseprofile":"e72be56f-4d0e-493c-a2c1-afc70f0e7d81",
        "buildallipa":true
    }
]